/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class craigacp_feast_FEAST */

#ifndef _Included_craigacp_feast_FEAST
#define _Included_craigacp_feast_FEAST
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     craigacp_feast_FEAST
 * Method:    BetaGamma
 * Signature: (I[[I[IDD)Lcraigacp/feast/ScoredFeatures;
 */
JNIEXPORT jobject JNICALL Java_craigacp_feast_FEAST_BetaGamma
  (JNIEnv *, jclass, jint, jobjectArray, jintArray, jdouble, jdouble);

/*
 * Class:     craigacp_feast_FEAST
 * Method:    feast
 * Signature: (II[[I[I)Lcraigacp/feast/ScoredFeatures;
 */
JNIEXPORT jobject JNICALL Java_craigacp_feast_FEAST_feast
  (JNIEnv *, jclass, jint, jint, jobjectArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
