/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class craigacp_feast_WeightedFEAST */

#ifndef _Included_craigacp_feast_WeightedFEAST
#define _Included_craigacp_feast_WeightedFEAST
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     craigacp_feast_WeightedFEAST
 * Method:    weightedFeast
 * Signature: (II[[I[I[D)Lcraigacp/feast/ScoredFeatures;
 */
JNIEXPORT jobject JNICALL Java_craigacp_feast_WeightedFEAST_weightedFeast
  (JNIEnv *, jclass, jint, jint, jobjectArray, jintArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
